"""Host-side transcript redaction — runs BEFORE any transcript text becomes LM context.

`CLAUDE.md` invariant (3): sensitive transcript content is redacted in the ingestion layer, not
left to the planner's judgement. `session.run_distillation` calls `redact_transcript` on every
transcript immediately after the adapter's single `ingest()`, and the redacted list is the ONLY one
threaded into `DistillSession` (both the constructor's `read_transcript_chunk` closure and the
`.arun(transcripts=...)` signature binding) — so there is no path left that hands the model raw text.

THREE TIERS, in this order:

1. **The hand-written patterns** (`_TIER1`) — seven shapes this project owns outright.
2. **A vendored, mechanically-ported subset of gitleaks' rules** (`_TIER2`, 120 rules loaded from
   `patterns/gitleaks_subset.json`, generated by `scripts/port_gitleaks.py`; see `VENDOR.md`).
3. **The operator's OWN rules** (`_TIER3`) — a JSON file named by the `CD_REDACTIONS` env var, for
   the credential shapes only the person running this knows about (a corporate token format, an
   internal header). Empty unless set. See "Tier three" below for the schema and the four checks
   every rule must survive at LOAD time.

**TIER THREE IS ADDITIVE ONLY. It can never disable, override or narrow tiers one and two.** That is
a DELIBERATE divergence from the `TS_TOOLSPACE` convention this feature otherwise mirrors, and it is
written down in three places (here, `.env.example`, `README.md`) precisely so nobody "fixes" it back
into symmetry. In toolscout, `TS_TOOLSPACE` REPLACES the built-in catalog and that is safe: the worst
case of a bad toolspace is FEWER TOOLS. Here the worst case of a replaced catalog is a LEAKED
CREDENTIAL. So the operator's file is appended to a floor it cannot lower — there is no `disable`
key, no label-shadowing, and no ordering knob.

**Tier one is not redundant with tier two, and it must stay FIRST.** That is a measured claim, not
a courtesy to the older code. Exactly TWO of the seven are genuinely UNAVAILABLE from gitleaks:

* `bearer_token` is anchored with a LOOKBEHIND (`(?<=authorization:\\s)`). RE2 cannot express
  lookbehind at all, so no gitleaks rule ever will.
* `secret_assignment` substitutes the VALUE ONLY, keeping `api_key = ` visible so a reviewer can
  still see WHAT was set. Every gitleaks rule replaces a token, never a value inside a binding.

And the decisive argument is not about any single pattern: on a real rendered Claude Code transcript,
the operator's own live API key — an `sk-<uuid-shaped>` PRIVATE-PROXY key — was **not** matched by
any of the 120 gitleaks rules, because it is not a known provider format. Tier one's `api_key`
caught it. An anchored corpus of known vendor prefixes is structurally blind to keys minted by
whoever is in front of you.

FIVE of the seven hand-written patterns ARE redundant with a vendored rule today, and they stay
anyway: `private_key`/`private-key`, `aws_access_key_id`/`aws-access-token`, `github_token`/
`github-pat`, `google_api_key`/`gcp-api-key`, and `api_key` against the several `sk-` vendor rules
(though only for the vendors upstream knows — see above). Tier two is REGENERATED from a moving
upstream, so a refresh that renamed or narrowed one of those would reduce coverage with no signal
anywhere; tier one is the floor that survives it. `tests/test_redact_golden.py`'s `_OVERLAP` table
asserts both halves so the loss surfaces as a red test saying "this shape is now tier-one-only".
`google_api_key` is not even fully redundant now — `gcp-api-key` requires a terminator from a fixed
set where this one ends on `\b`, so `AIza<35>]` is tier-one-only.

CORRECTED per an adversarial review: this used to claim `private_key` was "a DOTALL BEGIN/END block
matcher gitleaks has no equivalent for — RE2 scans line-oriented and upstream's private-key rules
match the header, not the body." That is FALSE, and it was verified false. The vendored `private-key`
rule is `(?i)-----BEGIN[ A-Z0-9_-]{0,100}PRIVATE KEY(?: BLOCK)?-----[\\s\\S-]{64,}?KEY(?: BLOCK)?-----`
— `[\\s\\S]` is RE2's own DOTALL idiom, and it matched a full 202-character block at span (0, 202),
body included. `private_key` keeps its place in tier one on the SAME ground as the other four
redundancies (refresh resilience), not on a capability gitleaks lacks. The paragraph above had
already contradicted itself by listing the pair as redundant-today eight lines later.

Cost, measured on the 426 KB rendered transcript: tier one ~32 ms, both tiers ~110 ms; ~135 ms at
512 KB, plus ~6 ms for one tier-three rule. Zero false positives on real transcript content — the
only tier-two hits were credential SHAPES a past session had already pasted in as its own test
fixtures. Dropping the five most expensive gitleaks rules saved 33 ms for five fewer rules, so all
120 ship. Coverage over shaped provider tokens went 4/14 (tier one alone) to 14/14.

HONEST SCOPE: this is pattern-based and BEST-EFFORT, not a claim of complete secret detection. It
catches credential SHAPES; it cannot catch a secret that looks like prose, a novel token format, or
a password the user typed inline. A human should still eyeball a transcript before sharing a plan
widely. Matches are replaced by a LABELLED placeholder (`[REDACTED:api_key]`,
`[REDACTED:github-pat]`) rather than deleted, so the plan can still say "a credential appeared
here" without carrying it.

NO NETWORK, EVER, and no new dependency. Only stdlib `re`/`json`/`os`/`time`. TruffleHog's model
(POST the candidate secret to the vendor's API to see whether it is live) is the exact inversion of
this module's purpose: this runs over the operator's own private history, so shipping a candidate
secret anywhere to grade it would BE the leak. And redaction is on the core path
(`session.run_distillation` calls it unconditionally), so it may never drag in an HTTP stack.
"""

from __future__ import annotations

import json
import os
import re
import time
import warnings
from collections.abc import Iterator, Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import NoReturn

from . import regex_walk

# --------------------------------------------------------------------------------------------
# Tier one — the hand-written patterns. Unchanged, and applied FIRST (see the module docstring).
# --------------------------------------------------------------------------------------------

# (label, compiled pattern). Order matters only where one shape could nest inside another; the
# private-key block is listed first so its body is consumed whole rather than piecemeal.
_TIER1: list[tuple[str, re.Pattern[str]]] = [
    (
        "private_key",
        re.compile(
            r"-----BEGIN[ A-Z]*PRIVATE KEY-----.*?-----END[ A-Z]*PRIVATE KEY-----",
            re.DOTALL,
        ),
    ),
    # `Authorization: Bearer <token>` / `authorization: token <token>` header values.
    (
        "bearer_token",
        re.compile(
            r"(?i)(?<=authorization:\s)(?:bearer|token)\s+[A-Za-z0-9\-._~+/]{8,}=*",
        ),
    ),
    # Provider API keys: an `sk-`/`sk-ant-`/`pk-` prefix plus a long opaque tail. THIS is the
    # pattern that catches a private-proxy key no vendor-specific gitleaks rule knows about.
    ("api_key", re.compile(r"\b(?:sk|pk)-(?:[A-Za-z0-9]+-)?[A-Za-z0-9_\-]{20,}")),
    # AWS access key ids.
    ("aws_access_key_id", re.compile(r"\b(?:AKIA|ASIA)[0-9A-Z]{16}\b")),
    # GitHub personal-access / app tokens.
    ("github_token", re.compile(r"\bgh[pousr]_[A-Za-z0-9]{16,}\b")),
    # Google API keys.
    ("google_api_key", re.compile(r"\bAIza[0-9A-Za-z_\-]{35}\b")),
    # An explicit `password = "..."` / `api_key: '...'` assignment — the value only.
    (
        "secret_assignment",   # == _ASSIGNMENT_LABEL, defined below (its replacement is special)
        re.compile(
            r"(?i)(?<=\b)(?P<key>password|passwd|secret|api[_-]?key|access[_-]?token)"
            r"(?P<sep>\s*[:=]\s*)(?P<quote>[\"']?)(?P<value>[^\s\"',;]{6,})(?P=quote)"
        ),
    ),
]


#: The one pattern whose replacement keeps surrounding text (the `key = ` part), so a reviewer can
#: still see WHAT was set without seeing the value.
_ASSIGNMENT_LABEL = "secret_assignment"


# --------------------------------------------------------------------------------------------
# Tier two — the vendored gitleaks subset.
# --------------------------------------------------------------------------------------------

#: The generated artifact. `scripts/port_gitleaks.py` writes it; never hand-edit it.
_SUBSET_PATH = Path(__file__).resolve().parent / "patterns" / "gitleaks_subset.json"


@dataclass(frozen=True)
class _GitleaksRule:
    """One ported upstream rule, precompiled at import."""

    rule_id: str
    pattern: re.Pattern[str]
    #: Lowercased upstream keywords. The rule is skipped unless one of them occurs in the text.
    gate: tuple[str, ...]
    #: True when the pattern has exactly one unnamed group, which upstream uses for the secret
    #: itself; the rest of the match is the surrounding delimiter and must survive.
    secret_is_group_one: bool
    #: gitleaks' entropy floor, carried for PROVENANCE and deliberately NOT enforced. See below.
    entropy: float | None


# THE KEYWORD GATE is kept exactly as upstream ships it — a rule runs only if one of its keywords
# occurs somewhere in the (lowercased) text. Two properties of that are worth stating plainly,
# because both were measured rather than assumed:
#
# * It is what makes the corpus SAFE, not merely fast. `sourcegraph-access-token` carries a bare
#   `[a-fA-F0-9]{40}` alternative — that is every git SHA-1 ever printed. Its `sgp_`/`sourcegraph`
#   keywords are the only thing standing between this redactor and `[REDACTED:...]` in place of
#   every commit hash in a coding transcript. An earlier draft here ungated any rule whose keywords
#   were not literally implied by its own pattern (to protect the vendor-name rules below); on the
#   real 426 KB transcript that immediately redacted a genuine commit SHA, so it was reverted. The
#   gate is also a 5.3x speedup (77 ms gated vs 406 ms ungated on that corpus), but correctness is
#   the reason it stays.
# * It has a known FALSE-NEGATIVE direction, stated rather than hidden. EXACTLY TWO of the 120 rules
#   are keyed on the vendor's NAME rather than on anything the token's own shape implies, so a bare
#   token in a transcript that never names the vendor is not reached:
#     - `airtable-personnal-access-token` — `pat<14 alnum>.<64 hex>`, gated on `airtable`;
#     - `facebook-access-token` — `\d{15,16}(\||%)[0-9a-z\-_]{27,40}`, gated on `facebook`.
#   That enumeration is MECHANICAL, not a hand-kept list: `tests/test_redact_golden.py` derives a
#   matching string for every rule from its own parse tree and asserts that exactly these two fail
#   their own keyword gate. (An earlier version of this comment named only Airtable and said "a few",
#   which is how the second one stayed invisible.) Upstream's own regression corpus cannot show the
#   gap — its generated samples embed the identifier — and `tests/test_redact_golden.py` pins that
#   all 85 golden true positives DO carry their own keyword.
#
# And some keywords are too short to gate anything at all: `jwt`'s is `ey`, `vault-service-token`'s
# is `s.` — both near-universal in English prose, so those rules effectively always run. That is
# inherent to upstream's keyword choice, not something to work around.


def _load_gitleaks_subset(path: Path = _SUBSET_PATH) -> tuple[_GitleaksRule, ...]:
    """Load + precompile the ported subset at import time.

    Compiles under `warnings.simplefilter("error")` for the reason spelled out in
    `scripts/port_gitleaks.py`: an unported POSIX class such as `[[:alnum:]]` compiles happily in
    Python with only a `FutureWarning` and then matches something else entirely, which in a
    REDACTOR means a live credential flows to the model with no error anywhere. A hand-edit that
    reintroduces one must fail loudly here rather than degrade silently.

    Deliberately NOT defensive about a missing or malformed artifact either: a packaging accident
    that dropped the file would leave a redactor quietly 120 rules weaker, and a redactor that
    silently gets weaker is the failure this module is built to avoid.
    """
    document = json.loads(path.read_text(encoding="utf-8"))
    rules: list[_GitleaksRule] = []
    # `re.compile` caches by (pattern, flags), and a cache HIT never re-parses — so it never re-emits
    # the `FutureWarning` the strict compile below is here to catch. Without this purge the guard is
    # only as good as whatever happened to run first in the process: an adversarial review primed the
    # cache with the raw Airtable POSIX pattern and then watched a hand-edited artifact carrying that
    # same pattern import CLEANLY, shipping a dead rule. `_rule_from_entry` and
    # `scripts/port_gitleaks.py` both purge for this exact reason; this loader was the odd one out.
    re.purge()
    with warnings.catch_warnings():
        warnings.simplefilter("error")
        for entry in document["rules"]:
            pattern = re.compile(entry["regex"])
            rules.append(
                _GitleaksRule(
                    rule_id=entry["id"],
                    pattern=pattern,
                    gate=tuple(k.lower() for k in entry.get("keywords") or ()),
                    secret_is_group_one=pattern.groups == 1 and not pattern.groupindex,
                    entropy=entry.get("entropy"),
                )
            )
    return tuple(rules)


_TIER2: tuple[_GitleaksRule, ...] = _load_gitleaks_subset()

# ENTROPY: a deliberate divergence from upstream, and the reason is the cost asymmetry.
#
# gitleaks attaches a Shannon-entropy floor to many rules and drops a match that falls below it.
# That is tuned for a SCANNER, where a false positive costs an engineer a few minutes of triage and
# a false negative costs a missed finding in a repo someone else will also scan. Here the roles are
# INVERTED: a false positive costs the literal string `[REDACTED:github-pat]` appearing in text a
# planner reads — which is exactly what this module already says it wants — while a false negative
# ships a live credential into a language model's context. Nothing downstream can undo that.
#
# The floors also earn their keep in upstream's *generic* rules, whose confidence comes from a
# nearby keyword rather than from the token itself. `scripts/port_gitleaks.py` already dropped all
# 101 of those: everything in `_TIER2` is anchored on a distinctive literal shape, so the prefix IS
# the evidence and the floor is redundant confidence bought with false negatives.
#
# So `entropy` is loaded and carried for provenance, and never applied. Measured against upstream's
# own regression corpus (`tests/data/gitleaks_golden.json`): all 85 true positives match either
# way, and dropping the floors redacts 33 additional credential-SHAPED strings that gitleaks
# tolerates — documentation samples and placeholders like `AIzaaaaaaaa…`. Over-redacting those
# costs the planner nothing. `tests/test_redact_golden.py` pins both halves.


def _placeholder(label: str) -> str:
    return f"[REDACTED:{label}]"


def _replace_assignment(match: re.Match[str]) -> str:
    """Keep `key`, the separator, and the quoting; replace only the value."""
    quote = match.group("quote")
    return (
        f"{match.group('key')}{match.group('sep')}{quote}"
        f"{_placeholder(_ASSIGNMENT_LABEL)}{quote}"
    )


def _apply_gitleaks_rule(rule: _GitleaksRule, text: str) -> str:
    """Substitute one ported rule, replacing the secret and keeping its delimiters.

    Most upstream rules wrap the credential in a single group and let the match run one character
    past it, onto the closing quote/backtick/semicolon that proves the token ended. Replacing the
    whole match would eat that delimiter and corrupt the surrounding line, so a single-unnamed-group
    rule substitutes group 1 in place. Everything else (no groups, or several — `jwt-base64` has 34
    named ones, none of which is the token) replaces the whole match, the over-redacting direction.
    """
    replacement = _placeholder(rule.rule_id)

    def _replace(match: re.Match[str]) -> str:
        if not rule.secret_is_group_one or match.group(1) is None:
            return replacement
        whole = match.group(0)
        offset = match.start()
        start, end = match.span(1)
        return whole[: start - offset] + replacement + whole[end - offset :]

    return rule.pattern.sub(_replace, text)


# --------------------------------------------------------------------------------------------
# Tier three — the operator's own rules, named by `CD_REDACTIONS`. ADDITIVE ONLY (see the module
# docstring). Modelled on toolscout's `TS_TOOLSPACE`: an env var naming a JSON file, a checked-in
# `redactions.example.json` you `cp` and edit.
# --------------------------------------------------------------------------------------------

#: The env var naming the operator's own rule file. Unset (or empty) means "no third tier".
REDACTIONS_ENV_VAR = "CD_REDACTIONS"

#: One rule's CLOSED key set. An unknown key is REFUSED rather than ignored, because the failure it
#: prevents is silent: a mistyped `replace_group` would quietly mean "replace the whole match", which
#: is a behaviour change (the surrounding `key = ` disappears) with no error anywhere.
_RULE_KEYS = frozenset({"label", "regex", "description", "sample", "replace_group"})

#: Every one of these must be a non-empty string. `sample` is mandatory FOR A REASON — see
#: `_check_sample`. `description` is mandatory because a redaction rule nobody can explain is a rule
#: nobody can audit, and the schema's own example uses it to record what the rule is known NOT to
#: catch. `replace_group` is the only optional key.
_REQUIRED_KEYS = ("label", "regex", "description", "sample")


@dataclass(frozen=True)
class OperatorRule:
    """One operator-supplied rule, compiled + calibrated + sample-checked at load."""

    label: str
    pattern: re.Pattern[str]
    description: str
    sample: str
    #: The NAME of a group in this rule's own regex whose span alone is replaced, leaving the rest of
    #: the match intact (`X-Internal-Auth: <value>` keeps the header name). `None` replaces the whole
    #: match. A closed vocabulary: the only legal values are `null` and a group the regex declares.
    replace_group: str | None


# ReDoS: REFUSED AT LOAD, not survived at run time.
#
# An operator regex runs on Python's BACKTRACKING `re` over transcripts of ~500 KB, and `re` has no
# timeout. The obvious fix — the third-party `regex` module, which does have one — is out: redaction
# is on the CORE path (`session.run_distillation` calls it unconditionally), and this module's whole
# posture is "no new runtime dependency, stdlib only".
#
# So the mitigation is CALIBRATION. Every rule is run against a grid of short synthetic adversarial
# strings, ascending in length, and refused on either of TWO gates. Both are needed; each catches
# what the other misses, and an adversarial review produced a live counter-example for each.
#
# GATE 1 — GROWTH RATIO, the primary detector. Catastrophic backtracking is EXPONENTIAL in the input
# length, so it is visible as a blowing-up RATIO between adjacent probe lengths long before any one
# probe is expensive. Measured on this machine, every classic shape (`(\w+\s?)+$`, `(a+)+$`,
# `(a|a)+$`, `(\d+)+$`, `([A-Za-z0-9]+)*$`, `(x+x+)+y`, `([a-zA-Z0-9_.-]+)+@corp\.example$`) grows by
# a remarkably consistent ~4.0x per TWO extra characters — i.e. base-2 per character — so a rule is
# refused the first time a probe costs `_GROWTH_FLOOR_SECONDS` or more AND at least
# `_GROWTH_RATIO`x its own predecessor two characters shorter. Every catastrophic shape below is
# refused within ~200 ms of load, where the old absolute-only gate paid 30-320 ms or hung outright.
#
# The floor is what makes the ratio safe: a well-behaved pattern never reaches 5 ms on a <=32-byte
# probe at all (the slowest of the 127 BUILT-INS is ~1.6 us for the grid's worst probe, a ~3000x
# margin, and `tests/test_redact_operator.py` pins that measurement rule by rule), so gate 1 cannot
# fire on one. Below the floor the ratio is ignored entirely, because a timing that small is
# scheduler noise. A breach is then re-timed (`_settled_cost`) and the SMALLEST measurement decides,
# because a refusal is fatal and permanent while a descheduled interpreter is neither — this suite
# really did see a good rule refused by a spike when another process loaded the machine.
#
# GATE 1 IS ALSO WHAT BOUNDS THE LOAD COST, and that is why the ladder now starts at TWO characters.
# The old grid started at 12 and measured elapsed time only AFTER `search` returned, so a pattern
# already astronomical at the smallest probe wedged the import with no bound at all: the adversarial
# review's `(a?a?a?a?a?a?a?a?a?a?)+$` costs 16.8 ms at 4 characters and 3.3 SECONDS at 6, and the old
# calibration simply never returned. At 2 characters it costs 88 us, so the ratio gate sees
# 88 us -> 16.8 ms and refuses having spent ~34 ms.
#
# GATE 2 — THE ABSOLUTE BUDGET, 20 ms per probe. It catches what a ratio cannot: POLYNOMIAL
# backtracking, where each step is only ~1.5-2x the last but the constant is ruinous.
# `a*a*a*a*a*a*b` (degree-7) passes gate 1 forever — its ratio is below 2 by the time it is above the
# floor — and still needs 22.8 ms at 28 characters, i.e. far longer than this project's patience for
# a 500 KB transcript. Anything needing more than 20 ms to scan 32 bytes will never finish a real
# transcript, and anything well-behaved is four orders of magnitude under it.
#
# THE PROBE ALPHABET. A fixed alphabet cannot trigger every pattern's blow-up, so the grid is
# extended from the pattern's own source in two ways, and BOTH are load-bearing:
#   * its distinct literal CHARACTERS (`_literal_seeds`) — `(x+x+)+y` needs a run of literal `x`.
#     ALL of them, not a prefix: an earlier cap of six let `(?:abcdef)?(z+z+)+Q` through, because `z`
#     was the seventh distinct literal and so never became a seed.
#   * its REACHING PREFIXES (`_reaching_prefixes`), emitted as a prefix followed by filler — the
#     common operator rule shape is a literal marker plus a quantified tail
#     (`CORPSECRETPREFIX-(\w+\s?)+$`, `X-Internal-Auth: ...`), and a probe made of single repeated
#     characters never spells the marker, so the pattern fails at position 0 and the tail is never
#     reached. That rule cost 1172 ms on `"CORPSECRETPREFIX-" + "a"*24` while calibration passed in
#     0.3 ms.
#
# THE PREFIX COMES FROM THE PARSE TREE, not from scraping the pattern TEXT, and that was the third
# adversarial review's HIGH finding. The scraper took literal RUNS of >=3 characters, which a real
# operator rule can trivially fail to contain — reproduced through the real loader:
#   * `X-(\w+\s?)+$` — a 2-character marker, under the 3-character minimum: loaded in ~107 ms, then
#     hung for over 15 SECONDS on a 46-character line.
#   * `ORG-[0-9]{4}-(\w+\s?)+$` — a marker with a CHARACTER CLASS in it. The scraped run was `ORG-`
#     and no filler spells `1234-`, so the tail was never reached at any marker length.
#   * `XY-(\w+\s?)+$` was caught, which is what made the cutoff exactly 3 and the hole invisible.
# Lowering the minimum to 1 would have closed only the first. `regex_walk.reaching_prefixes` walks
# the pattern's own `re` parse tree instead, emitting a concrete string for every literal, class and
# bounded repeat until it reaches an ambiguous quantifier — so all three shapes (and a backreference,
# and a leading lookbehind) produce a prefix that actually reaches the tail. It shares that walk with
# `scripts/derive_liveness_samples.py` rather than keeping a second copy of it.
#
# GATE 1 BOUNDS THE PER-PROBE COST; `_MAX_REACHING_PREFIXES` IS WHAT BOUNDS THE AGGREGATE. Probe
# COUNT used to be unbounded in the pattern's length — the same review's 7,919-alternative pattern
# produced 1,014,880 probes and a 16.8 s load, every individual one of them cheap. The two derived
# families are now bounded independently: `_literal_seeds` by the alphabet itself (at most 62
# distinct alphanumerics plus their concatenation), `_reaching_prefixes` by an explicit cap. So the
# whole grid is at most
#   len(_PROBE_LENGTHS) * (seeds * len(_PROBE_TAILS)
#                          + _MAX_REACHING_PREFIXES * len(_RUN_FILLERS) * len(_PROBE_TAILS))
# probes — about 6.5k, whatever the pattern looks like.
#
# HONEST SCOPE, because this is a heuristic and not a proof. Three gaps remain and none is closed:
# a sufficiently contrived pattern can still evade any finite probe set (nothing here derives the
# input that MAXIMISES backtracking); the load cost is bounded only DOWN TO the smallest probe — a
# pattern that is already astronomical on a 2-character input would still wedge the import, because
# there is no way to time a search without running it; and the filler that follows a reaching prefix
# comes from the fixed `_RUN_FILLERS`, so a marker followed by a tail keyed on some OTHER character
# (`X-(z+z+)+Q`) is reached but not fed. Every shape tried so far is cheap at 2 characters
# (exponential blow-up needs input length to work with), but that is an observation, not a guarantee.
# This turns the common accidents into startup errors; it is not a decision procedure for regex
# complexity.
_REDOS_BUDGET_SECONDS = 0.020
#: Below this a timing is scheduler noise, so gate 1 ignores the ratio entirely. 4x under the
#: absolute budget and ~3000x over the slowest built-in probe (~1.6 us, best of five), which is the
#: margin that keeps a loaded CI box from refusing a well-behaved rule.
_GROWTH_FLOOR_SECONDS = 0.005
#: Growth per TWO extra probe characters that implies exponential backtracking. Every classic
#: catastrophic shape measures ~4.0x here; a linear or quadratic scanner measures well under 2x.
_GROWTH_RATIO = 3.0
#: Extra measurements a BREACHING probe gets before it is believed. Wall-clock timing on a loaded
#: machine spikes; the smallest of several runs is the honest cost. Stops at the first measurement
#: under the threshold, so a spike costs one extra run and a genuinely bad pattern costs three.
_CONFIRM_RUNS = 3
_PROBE_LENGTHS = (2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32)
_PROBE_SEEDS = ("a", "0", "ab", "a ", "aA0", "a-", "a.", "a=", "a/", "a_", "aaaa-", "aaaa.", "aaaa ")
#: A trailing non-word character forces the FAILED match that makes a backtracker enumerate.
_PROBE_TAILS = ("", "!")
#: What follows a REACHING PREFIX in a prefixed probe — the quantified tail's food.
_RUN_FILLERS = ("a", "0", "a ", "aA0")
#: How many reaching prefixes one pattern may contribute. THE AGGREGATE LOAD BOUND — see the two
#: paragraphs above; without it a pattern with thousands of alternatives makes calibration itself
#: the denial of service it exists to prevent.
_MAX_REACHING_PREFIXES = 32


def _refuse(message: str) -> NoReturn:
    """Every tier-three load failure lands here: loud, named, and fatal.

    `SystemExit` rather than a warning-and-continue path, for the same reason `_load_gitleaks_subset`
    is deliberately not defensive about a missing artifact: a redactor that silently gets WEAKER is
    the exact failure this module exists to avoid. Failing closed at startup is recoverable; shipping
    a live credential into a model's context is not.
    """
    raise SystemExit(f"{REDACTIONS_ENV_VAR}: {message}")


def _literal_seeds(source: str) -> list[str]:
    """EVERY distinct ASCII-alphanumeric LITERAL a pattern mentions, as extra probe seeds.

    A fixed alphabet cannot make `(x+x+)+y` backtrack — nothing in it is an `x`. Feeding a pattern
    its own literal characters closes that gap for the realistic case, cheaply and mechanically.
    Backslash escapes are skipped so `\\w` contributes no `w`; a character-class body contributes its
    endpoints, which is harmless (they are plausible probe characters either way).

    ALL of them, deliberately — there is no cap. An earlier version took the first six, which is how
    `(?:abcdef)?(z+z+)+Q` passed calibration in 0.3 ms and then cost 790 ms on 24 `z`s: `z` was the
    seventh distinct literal. The count is bounded by the pattern's own length anyway.
    """
    chars: list[str] = []
    skip = False
    for char in source:
        if skip:
            skip = False
        elif char == "\\":
            skip = True
        elif char.isascii() and char.isalnum() and char not in chars:
            chars.append(char)
    seeds = list(chars)
    if len(seeds) > 1:
        seeds.append("".join(chars))
    return [seed for seed in seeds if seed not in _PROBE_SEEDS]


def _reaching_prefixes(source: str) -> list[str]:
    """Concrete prefixes that reach the pattern's ambiguous quantifiers — from its PARSE TREE.

    The MOST COMMON operator rule shape is a marker followed by a quantified tail —
    `CORPSECRETPREFIX-(\\w+\\s?)+$`, `X-Internal-Auth:\\s*([\\w=]+)+$`, and `redactions.example.json`'s
    own `corp-internal-token`. A probe made of one repeated character never spells the marker, so the
    match fails at position 0 and the catastrophic tail is never reached. `_probes` emits each prefix
    with filler after it, which is what actually reaches the tail.

    A thin wrapper over `regex_walk.reaching_prefixes` — the SAME parse-tree walk
    `scripts/derive_liveness_samples.py` derives its samples from — pinning this module's own cap on
    how many prefixes one pattern may contribute. It replaced a scraper that read literal RUNS out of
    the pattern TEXT, which could not spell a 2-character marker or one containing a character class;
    see the calibration commentary above for the reproductions.
    """
    return regex_walk.reaching_prefixes(source, limit=_MAX_REACHING_PREFIXES)


def _probes(source: str) -> Iterator[tuple[int, str, tuple[str, ...]]]:
    """The adversarial probe grid, SHORTEST FIRST, as `(length, probe, family)`.

    Ascending length is what lets gate 2 abort early; `family` is what lets gate 1 compare a timing
    against the SAME probe shape two characters shorter rather than against an unrelated one. Both
    derived families are BOUNDED (see `_MAX_REACHING_PREFIXES`), so the grid's size is too.
    """
    seeds = (*_PROBE_SEEDS, *_literal_seeds(source))
    prefixes = _reaching_prefixes(source)
    for length in _PROBE_LENGTHS:
        for seed in seeds:
            body = (seed * (length // len(seed) + 1))[:length]
            for tail in _PROBE_TAILS:
                yield length, body + tail, ("seed", seed, tail)
        for prefix in prefixes:
            for filler in _RUN_FILLERS:
                body = (filler * (length // len(filler) + 1))[:length]
                for tail in _PROBE_TAILS:
                    yield length, prefix + body + tail, ("prefix", prefix, filler, tail)


def _time_search(pattern: re.Pattern[str], probe: str) -> float:
    start = time.perf_counter()
    pattern.search(probe)
    return time.perf_counter() - start


def _settled_cost(pattern: re.Pattern[str], probe: str, elapsed: float, threshold: float) -> float:
    """The SMALLEST cost `probe` really has, once a suspicious timing has been re-checked.

    A refusal is permanent and fatal, so no gate may fire on a single wall-clock reading: this suite
    genuinely saw a well-behaved rule refused because another process on the box descheduled the
    interpreter mid-`search`. Re-timing stops the moment one run comes in under `threshold`, so the
    cost of noise is one extra run and the cost of a real breach is `_CONFIRM_RUNS` of a probe that
    the gate catching it has already bounded.
    """
    for _ in range(_CONFIRM_RUNS):
        if elapsed < threshold:
            return elapsed
        elapsed = min(elapsed, _time_search(pattern, probe))
    return elapsed


def _calibrate(where: str, pattern: re.Pattern[str]) -> None:
    """Refuse a pattern that backtracks catastrophically — see the two-gate commentary above."""
    previous: dict[tuple[str, ...], float] = {}
    for _length, probe, family in _probes(pattern.pattern):
        elapsed = _time_search(pattern, probe)

        # Gate 1 — exponential GROWTH against this family's own previous length. Ignored below the
        # noise floor, where a timing says nothing at all.
        before = previous.get(family)
        if before is not None and elapsed >= _GROWTH_FLOOR_SECONDS and elapsed >= before * _GROWTH_RATIO:
            threshold = max(_GROWTH_FLOOR_SECONDS, before * _GROWTH_RATIO)
            elapsed = _settled_cost(pattern, probe, elapsed, threshold)
            if elapsed >= threshold:
                _refuse(
                    f"{where}: cost grew {elapsed / before:.0f}x ({before * 1000:.2f} ms -> "
                    f"{elapsed * 1000:.2f} ms) for two more probe characters — it backtracks "
                    f"catastrophically (exponentially in the input length) and would hang on a real "
                    f"transcript, which Python's `re` cannot time out. Probe: {probe!r}. "
                    f"Rewrite it without nested/ambiguous quantifiers."
                )

        # Gate 2 — the absolute per-probe BUDGET, for polynomial blow-up that grows too gently to
        # trip gate 1 and is ruinous anyway.
        if elapsed > _REDOS_BUDGET_SECONDS:
            elapsed = _settled_cost(pattern, probe, elapsed, _REDOS_BUDGET_SECONDS)
            if elapsed > _REDOS_BUDGET_SECONDS:
                _refuse(
                    f"{where}: took {elapsed * 1000:.0f} ms to scan a {len(probe)}-character probe "
                    f"(budget {_REDOS_BUDGET_SECONDS * 1000:.0f} ms) — it backtracks catastrophically "
                    f"and would hang on a real transcript, which Python's `re` cannot time out. "
                    f"Probe: {probe!r}. Rewrite it without nested/ambiguous quantifiers."
                )

        previous[family] = elapsed


def _apply_operator_rule(rule: OperatorRule, text: str) -> str:
    """Substitute one operator rule — the whole match, or only `replace_group`'s span.

    The group form is the generic version of what tier one's `secret_assignment` does by hand: keep
    everything the match covered EXCEPT the named group, so `password = "…"` stays legible as
    `password = "[REDACTED:secret_assignment]"`. Independently useful — it is how you redact the value
    after `X-Internal-Auth:` without losing the header name.
    """
    replacement = _placeholder(rule.label)
    if rule.replace_group is None:
        return rule.pattern.sub(replacement, text)

    group = rule.replace_group

    def _replace(match: re.Match[str]) -> str:
        whole = match.group(0)
        start, end = match.span(group)
        if start < 0:  # an optional group that did not participate in THIS match
            return whole
        offset = match.start()
        return whole[: start - offset] + replacement + whole[end - offset :]

    return rule.pattern.sub(_replace, text)


#: How much of a `sample` a refusal is allowed to echo. `sample` is the one field the schema REQUIRES
#: to be credential-SHAPED, and a refusal goes to stderr — into scrollback, a CI log, a crash report.
#: The documentation (`.env.example`, `README.md`) says to use a synthetic value for that reason;
#: truncating is the belt to that braces, so a real credential pasted in by mistake is not reprinted
#: whole. Long enough that a realistic synthetic sample still shows in full.
_SAMPLE_ECHO_CHARS = 64


def _excerpt(text: str) -> str:
    """`repr` of at most `_SAMPLE_ECHO_CHARS` characters, marked when it was cut."""
    if len(text) <= _SAMPLE_ECHO_CHARS:
        return repr(text)
    return f"{text[:_SAMPLE_ECHO_CHARS]!r} (truncated, {len(text)} characters)"


def _check_sample(where: str, rule: OperatorRule) -> None:
    """EXECUTE the rule against its own `sample`. The single most valuable check in this tier.

    A regex that compiles but never matches gives false confidence — the operator believes a shape is
    covered, the redactor removes nothing, and there is no error anywhere. That is the same failure
    class as the Airtable POSIX trap `scripts/port_gitleaks.py` exists to catch, arriving through a
    different door. So `sample` is MANDATORY and it is RUN: the rule's own regex must redact it.

    The second half pins idempotence, which `redact_transcript` promises across every tier: applying
    the rule to its own output must be a no-op. A rule whose pattern matches its own
    `[REDACTED:<label>]` placeholder would otherwise grow the text on every pass.
    """
    redacted = _apply_operator_rule(rule, rule.sample)
    if redacted == rule.sample:
        _refuse(
            f"{where}: does NOT redact its own `sample` — the regex compiles but never matches the "
            f"one string the rule itself claims it catches. sample={_excerpt(rule.sample)}"
            + (
                f" (replace_group={rule.replace_group!r} may not have participated in the match)"
                if rule.replace_group is not None
                else ""
            )
        )
    if _apply_operator_rule(rule, redacted) != redacted:
        _refuse(
            f"{where}: is not idempotent — it re-matches its own {_placeholder(rule.label)!r} "
            f"placeholder, so every redaction pass would grow the text. Narrow the pattern so it "
            f"cannot match an already-redacted span."
        )


def _rule_from_entry(where: str, entry: object, seen: set[str]) -> OperatorRule:
    """Validate + compile + calibrate + sample-check ONE entry, or refuse loudly naming it."""
    if not isinstance(entry, dict):
        _refuse(f"{where} is a {type(entry).__name__}, not an object")
    unknown = sorted(set(entry) - _RULE_KEYS)
    if unknown:
        _refuse(f"{where}: unknown key(s) {unknown}; the schema is exactly {sorted(_RULE_KEYS)}")
    for key in _REQUIRED_KEYS:
        value = entry.get(key)
        if not isinstance(value, str) or not value.strip():
            _refuse(f"{where}: {key!r} is REQUIRED and must be a non-empty string")

    label = entry["label"]
    where = f"{where} ({label!r})"
    if "[" in label or "]" in label:
        _refuse(f"{where}: a label may not contain a bracket — it becomes '[REDACTED:<label>]'")
    if label in seen:
        _refuse(f"{where}: duplicate label; every rule's placeholder must name one rule")
    seen.add(label)

    replace_group = entry.get("replace_group")
    if replace_group is not None and (not isinstance(replace_group, str) or not replace_group):
        _refuse(f"{where}: 'replace_group' must be null, absent, or a non-empty group NAME")

    # Warnings-as-errors, for the reason `_load_gitleaks_subset` gives: an unported POSIX class
    # compiles in Python with only a `FutureWarning` and then means something else entirely. `purge`
    # first because `re.compile` caches by (pattern, flags) and a cache hit skips the parse that
    # emits the warning.
    re.purge()
    try:
        with warnings.catch_warnings():
            warnings.simplefilter("error")
            pattern = re.compile(entry["regex"])
    except (re.error, Warning) as exc:
        _refuse(f"{where}: 'regex' does not compile — {type(exc).__name__}: {exc}")

    if replace_group is not None and replace_group not in pattern.groupindex:
        available = sorted(pattern.groupindex) or ["<none — the regex declares no named groups>"]
        _refuse(
            f"{where}: 'replace_group' names {replace_group!r}, which its own regex does not "
            f"define. Available: {available}. Use `(?P<{replace_group}>…)` or set it to null."
        )

    rule = OperatorRule(
        label=label,
        pattern=pattern,
        description=entry["description"],
        sample=entry["sample"],
        replace_group=replace_group,
    )
    # Calibration runs BEFORE the sample check, and the order is load-bearing: `_check_sample` runs
    # the pattern over operator-supplied text, so a catastrophic pattern must already have been
    # refused by then.
    _calibrate(where, rule.pattern)
    _check_sample(where, rule)
    return rule


def load_operator_rules(path: Path | str) -> tuple[OperatorRule, ...]:
    """Load, validate and calibrate an operator redaction file. Refuses loudly, never silently.

    The file is a JSON LIST of `{label, regex, description, sample, replace_group?}` objects; see
    `redactions.example.json` at the repo root, which is a REAL working file (the seven built-in
    tier-one patterns expressed in this schema, plus one illustrative org-specific rule) rather than
    a fill-in-the-blank skeleton — and which `tests/test_redact_operator.py` loads through THIS
    function, so it cannot rot.

    Four checks per rule, each closing a way a redaction rule fails silently:

    1. the CLOSED key set (a mistyped key is a refusal, not an ignored line);
    2. strict compilation, warnings promoted to errors;
    3. ReDoS CALIBRATION against a synthetic adversarial probe grid under a wall-clock budget;
    4. the rule's own `sample`, EXECUTED — it must be redacted by the rule's own regex, and the
       result must be stable under a second pass.
    """
    source = Path(path)
    try:
        raw = source.read_text(encoding="utf-8")
    except OSError as exc:
        _refuse(f"cannot read {source} — {type(exc).__name__}: {exc}")
    try:
        document = json.loads(raw)
    except json.JSONDecodeError as exc:
        _refuse(f"{source} is not valid JSON — {exc}")
    if not isinstance(document, list):
        _refuse(f"{source} must hold a JSON LIST of rules, found a {type(document).__name__}")

    seen: set[str] = set()
    return tuple(
        _rule_from_entry(f"{source} rule #{position}", entry, seen)
        for position, entry in enumerate(document)
    )


def _load_operator_tier(env: Mapping[str, str] | None = None) -> tuple[OperatorRule, ...]:
    """Resolve `CD_REDACTIONS` at import. Unset or empty is the norm — an empty third tier."""
    configured = (os.environ if env is None else env).get(REDACTIONS_ENV_VAR, "").strip()
    if not configured:
        return ()
    return load_operator_rules(Path(configured).expanduser())


_TIER3: tuple[OperatorRule, ...] = _load_operator_tier()


def redact_transcript(text: str) -> str:
    """Return `text` with common secret shapes replaced by `[REDACTED:<label>]` placeholders.

    Deterministic and idempotent: a placeholder contains no pattern that would re-match, so
    redacting twice yields the same string (pinned across tiers one and two by
    `tests/test_redact_golden.py`, and enforced per-rule at LOAD time for tier three by
    `_check_sample`). Never raises — a non-string input is coerced with `str()` so an odd transcript
    entry degrades instead of breaking ingestion.

    Tier one runs first and wins any overlap, so a shape this project owns keeps its own stable
    label (`[REDACTED:github_token]`, not `[REDACTED:github-pat]`) no matter how the vendored
    corpus is refreshed. Tier three runs LAST, and only ever adds: by the time the operator's rules
    see the text, everything tiers one and two matched is already a placeholder.
    """
    out = text if isinstance(text, str) else str(text)
    for label, pattern in _TIER1:
        if label == _ASSIGNMENT_LABEL:
            out = pattern.sub(_replace_assignment, out)
        else:
            out = pattern.sub(_placeholder(label), out)

    # One lowered copy for every keyword gate. Built AFTER tier one on purpose: tier one only ever
    # removes secret text, so a keyword it consumed guarded nothing that is still there to match.
    lowered = out.lower()
    for rule in _TIER2:
        if rule.gate and not any(keyword in lowered for keyword in rule.gate):
            continue
        out = _apply_gitleaks_rule(rule, out)

    # Tier three, LAST and ADDITIVE ONLY — the operator's own shapes, on top of a floor they cannot
    # lower. Empty unless `CD_REDACTIONS` names a file (see the module docstring).
    for operator_rule in _TIER3:
        out = _apply_operator_rule(operator_rule, out)
    return out


def redact_all(texts: list[str]) -> list[str]:
    """Redact a whole transcript list — the shape `run_distillation` needs."""
    return [redact_transcript(t) for t in texts]
